FROM golang:1.24-alpine

WORKDIR /app

RUN apk add --no-cache openssl

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./

RUN go mod download

COPY . .

COPY scripts/init.sh /usr/local/bin/init.sh
RUN chmod +x /usr/local/bin/init.sh

EXPOSE 8080

ENTRYPOINT ["/usr/local/bin/init.sh"]

CMD ["air", "-c", ".air.toml"] 