version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_password_app_backend_prod
    volumes:
      - postgres_data_backend_prod:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=password_app
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: backend_password_app_prod_only
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=host=postgres user=postgres password=postgres dbname=password_app port=5432 sslmode=disable
    restart: unless-stopped

volumes:
  postgres_data_backend_prod: 