FROM golang:1.24-alpine AS builder

WORKDIR /app

RUN apk add --no-cache openssl

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o main .

FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache openssl

COPY scripts/init.sh /usr/local/bin/init.sh
RUN chmod +x /usr/local/bin/init.sh

COPY --from=builder /app/main .

EXPOSE 8080

ENTRYPOINT ["/usr/local/bin/init.sh"]

CMD ["./main"] 