version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_password_app_backend_dev
    volumes:
      - postgres_data_backend_dev:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend_password_app_dev_only
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/tmp
      - /go/pkg/mod
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - .env

volumes:
  postgres_data_backend_dev: 